name: observability
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      COLLECTOR_OTLP_ENABLED: 'true'
    ports:
      - '16686:16686'   # UI
      - '4318:4318'     # OTLP/HTTP
      - '4317:4317'     # OTLP/gRPC
      - '14250:14250'   # gRPC Jaeger ingest
      - '14268:14268'   # Thrift ingest
      - '14269:14269'   # Prometheus metrics
    networks:
      - observability
    restart: unless-stopped

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    env_file:
      - .env
    ports:
      - 3333:3333
    networks:
      - observability
    depends_on:
      jaeger:
        condition: service_started
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
      - '--web.route-prefix=/'
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    networks:
      - observability
    restart: unless-stopped
    depends_on:
      - api

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - observability
    restart: unless-stopped
    depends_on:
      - prometheus
      - jaeger

networks:
  observability:
    driver: bridge

volumes:
  grafana_data:
  prometheus_data: